---
- name: Ensure nginx paths exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nginx_path_ssl_conf }}"
    - "{{ nginx_path_vhosts_conf }}"
    - "{{ nginx_path_vhosts }}"
  notify: reload nginx

- name: Configure nginx (MIME types)
  template:
    src: mime.types.j2
    dest: "{{ nginx_path_mime_types_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: Configure nginx (main config)
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_path_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: Configure nginx (common SSL configuration)
  template:
    src: ssl-common.conf.j2
    dest: "{{ nginx_path_ssl_common_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
