---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

- import_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: configure.yml

- import_tasks: geoip.yml

- import_tasks: vhosts.yml

- name: Ensure nginx is started and enabled to start at boot
  service:
    name: nginx
    state: started
    enabled: true
