---
- name: Ensure nginx vhost paths exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nginx_path_vhosts_conf }}"
    - "{{ nginx_path_vhosts }}"
  notify: reload nginx

- name: Remove default nginx vhost config
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ nginx_path_vhosts }}/default"
    - "{{ nginx_path_vhosts_conf }}/default"
  notify: restart nginx

- name: Configure nginx (default server)
  template:
    src: vhost-default.j2
    dest: "{{ nginx_path_vhosts_conf }}/default.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: Enable default server
  file:
    state: link
    src: "{{ nginx_path_vhosts_conf }}/default.conf"
    dest: "{{nginx_path_vhosts }}/default.conf"
  notify:
   - reload nginx

- name: Configure nginx (sites)
  template:
    src: vhost_site.j2
    dest: "{{ nginx_path_vhosts_conf }}/{{ item.key }}.conf"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ nginx_sites }}"
  when: nginx_vhosts | length > 0
  notify:
    - reload nginx

- name: Configure nginx (SSL for sites)
  template:
    src: ssl-site.conf.j2
    dest: "{{ nginx_path_ssl_conf }}/{{ item.key }}.conf"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ nginx_sites }}"
  when: nginx_vhosts | length > 0
  notify:
    - reload nginx

- name: Enable sites
  file:
    state: link
    src: "{{ nginx_path_vhosts_conf }}/{{ item.key }}.conf"
    dest: "{{nginx_path_vhosts }}/{{ item.key }}.conf"
  with_dict: "{{ nginx_sites }}"
  when: nginx_vhosts | length > 0
  notify:
    - reload nginx
